coverage:
  status:
    project:
      default:
        target: 80%
comment:
  layout: 'reach, diff, flags'

flags:
  web3:
    paths:
      - /packages/web3/src
  web3-core:
    paths:
      - /packages/web3-core/src
  web3-errors:
    paths:
      - /packages/web3-errors/src
  web3-eth:
    paths:
      - /packages/web3-eth/src
  web3-eth-abi:
    paths:
      - /packages/web3-eth-abi/src
  web3-eth-accounts:
    paths:
      - /packages/web3-eth-accounts/src
  web3-eth-contract:
    paths:
      - /packages/web3-eth-contract/src
  web3-eth-ens:
    paths:
      - /packages/web3-eth-ens/src
  web3-eth-iban:
    paths:
      - /packages/web3-eth-iban/src
  web3-eth-personal:
    paths:
      - /packages/web3-eth-personal/src
  web3-net:
    paths:
      - /packages/web3-net/src
  web3-providers-http:
    paths:
      - /packages/web3-providers-http/src
  web3-providers-ipc:
    paths:
      - /packages/web3-providers-ipc/src
  web3-providers-ws:
    paths:
      - /packages/web3-providers-ws/src
  web3-rpc-methods:
    paths:
      - /packages/web3-rpc-methods/src
  web3-utils:
    paths:
      - /packages/web3-utils/src
  web3-validator:
    paths:
      - /packages/web3-validator/src
