coverage:
  status:
    project:
      default:
        target: 80%
      web3:
        flags: 
            - web3
      web3-core:
        flags: 
            - web3-core
      web3-errors:
        flags: 
            - web3-errors
      web3-eth:
        flags: 
            - web3-eth
      web3-eth-abi:
        flags: 
            - web3-eth-abi
      web3-eth-accounts:
        flags: 
            - web3-eth-accounts
      web3-eth-contract:
        flags: 
            - web3-eth-contract
      web3-eth-ens:
        flags: 
            - web3-eth-ens
      web3-eth-iban:
        flags: 
            - web3-eth-iban
      web3-eth-personal:
        flags: 
            - web3-eth-personal
      web3-net:
        flags: 
            - web3-net
      web3-providers-http:
        flags: 
            - web3-providers-http
      web3-providers-ipc:
        flags: 
            - web3-providers-ipc
      web3-providers-ws:
        flags: 
            - web3-providers-ws
      web3-rpc-methods:
        flags: 
            - web3-rpc-methods
      web3-utils:
        flags: 
            - web3-utils
      web3-validator:
        flags: 
            - web3-validator
    patch: off

comment:
  layout: 'reach, diff, flags, files'
  require_changes: false  
  require_base: yes
  require_head: yes       
  branches: null

flags:
  web3:
    paths:
      - /packages/web3/src/
  web3-core:
    paths:
      - /packages/web3-core/src/
  web3-errors:
    paths:
      - /packages/web3-errors/src/
  web3-eth:
    paths:
      - /packages/web3-eth/src/
  web3-eth-abi:
    paths:
      - /packages/web3-eth-abi/src/
  web3-eth-accounts:
    paths:
      - /packages/web3-eth-accounts/src/
  web3-eth-contract:
    paths:
      - /packages/web3-eth-contract/src/
  web3-eth-ens:
    paths:
      - /packages/web3-eth-ens/src/
  web3-eth-iban:
    paths:
      - /packages/web3-eth-iban/src/
  web3-eth-personal:
    paths:
      - /packages/web3-eth-personal/src/
  web3-net:
    paths:
      - /packages/web3-net/src/
  web3-providers-http:
    paths:
      - /packages/web3-providers-http/src/
  web3-providers-ipc:
    paths:
      - /packages/web3-providers-ipc/src/
  web3-providers-ws:
    paths:
      - /packages/web3-providers-ws/src/
  web3-rpc-methods:
    paths:
      - /packages/web3-rpc-methods/src/
  web3-utils:
    paths:
      - /packages/web3-utils/src/
  web3-validator:
    paths:
      - /packages/web3-validator/src/
