name: 'E2E Network Tests'
on:
    push:
      branches:
        - release/**
      tags:
        - v4.*
jobs:
  build:
    strategy:
      matrix:
        node: 14
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      - run: yarn
      - run: tar -czf /tmp/web3-${{ matrix.node }}.js.tar.gz --exclude="./.git" ./
      - uses: actions/upload-artifact@v3
        with:
          name: web3-${{ matrix.node }}.js.tar.gz
          path: /tmp/web3-${{ matrix.node }}.js.tar.gz
  e2e:
      name: E2E Network Tests
      needs: build
      runs-on: ubuntu-latest
      env:
        INFURA_SEPOLIA_HTTP: ${{ secrets.INFURA_SEPOLIA_HTTP }}
        INFURA_MAINNET_HTTP: ${{ secrets.INFURA_MAINNET_HTTP }}
        MODE: ${{ matrix.mode }}
        TEST_ACCOUNT_ADDRESS: fromJSON('{"sepolia":"0xa127C5E6a7E3600Ac34A9a9928E52521677e7211","mainnet":"0x0000000000000000000000000000000000000000"}')[matrix.network]
        ALLOWED_SEND_TRANSACTION: false
      strategy:
        fail-fast: false
        matrix:
          node: 14
          mode: ['http']
          network: ['sepolia', 'mainnet']
      steps:
        - uses: actions/download-artifact@v3
          with:
            name: web3-${{ matrix.node }}.js.tar.gz
            path: /tmp
        - run: tar -xf /tmp/web3-${{ matrix.node }}.js.tar.gz -C ./
        - run: |
            yarn test:e2e:${{ matrix.network }}:${{ matrix.mode }}
          shell: bash
